README.md
docs/user-guide.md

New demo video added for volume scheduling. 
Changes are also added to the k8shim to support these examples

Example updates for volumes (EBS added)

---

docs/setup/deployment.md
docs/user-guide.md

For simplicity, use helm charts for deployment in user guides.

Simplify the user guide with helm charts

---

go.mod
go.sum
pkg/common/commonevents/events.go
pkg/scheduler/scheduler.go

see more about https://github.com/cloudera/yunikorn-k8shim/issues/42

Scheduler core should notify shim to forget assumed pods to keep cache consistent

---

pkg/common/security/acl.go
pkg/common/security/acl_test.go

Fix for issue #49
This reverses commit: 68f42a5 and fixes the test

Fix unit test for special case ACL and clean up logging linked to it

---

go.mod
pkg/scheduler/sorters_test.go

Some simple UT to cover fairness testing.

add some unit tests to verify the correctness of queue fairness

---

pkg/scheduler/tests/scheduler_perf_test.go
pkg/scheduler/tests/schedulertestutils.go

Add new throughput tests (#69)

---

config/limit.yaml
config/queues.yaml
docs/queue_config.md
pkg/common/configs/config.go
pkg/common/configs/config_test.go
pkg/common/configs/configvalidator.go

- cleanup and doc of config
- extend validator to check user limit object on partition and queue
- extend config tests to include user limits

Add User limit objects to the queue in the config

---

pkg/cache/node_info.go
pkg/cache/partition_info.go
pkg/webservice/dao/node_info.go
pkg/webservice/handlers.go
pkg/webservice/routes.go

This is helpful for debugging issues on a prod cluster

[YUNIKORN-9] Add REST API to retrieve nodes info

---

pkg/scheduler/scheduling_queue.go

When adding a queue to the scheduler and updating the partition
configuration a data race occurs in the parent queue processing the
child queues.

[YUNIKORN-15] Fix data race in queue create

---

README.md

corrected typo from guidines to guidelines.

[YUNIKORN-27] corrected typo readme.md

---

Makefile
pkg/common/utils.go
pkg/scheduler/scheduler.go
pkg/scheduler/scheduling_application.go
pkg/scheduler/scheduling_node.go
pkg/scheduler/scheduling_partition.go
pkg/scheduler/scheduling_partition_test.go
pkg/scheduler/tests/scheduler_recovery_test.go
pkg/scheduler/tests/scheduler_reservation_test.go
pkg/scheduler/tests/scheduler_smoke_test.go

Production code fixes for incorrect logging only
Clean up of smoke test logic and unused code
Fix lint testing to use head ref from git

[YUNIKORN-30] fix flaky unit test

---

docs/user-guide.md

Add a tfjob example for yunikorn.

[YUNIKORN-171] Add example and document about how to run kubeflow with yunikorn

---

pkg/cache/initializer.go
pkg/cache/initializer_test.go
pkg/common/configs/config_test.go
pkg/common/resources/resources_test.go
pkg/scheduler/placement/rule_test.go
pkg/scheduler/scheduling_queue.go

This PR corrects some grammar mistakes found while reading the yk
source.

[YUNIKORN-191] Fix some grammar mistakes

---

docs/user-guide.md

[YUNIKORN-245] Add documents about the configurable options in yunikorn install via helm-charts

---

pkg/common/resources/resources.go

Reduced the log level from WARN to INFO

[YUNIKORN-428] Reduce the warning logs in resources.go

---

Makefile
go.mod
go.sum
pkg/common/utils.go
pkg/common/utils_test.go
pkg/scheduler/context.go
pkg/scheduler/objects/allocation.go
pkg/scheduler/objects/allocation_ask.go
pkg/scheduler/objects/allocation_ask_test.go
pkg/scheduler/objects/allocation_test.go
pkg/scheduler/objects/application.go
pkg/scheduler/objects/application_test.go
pkg/scheduler/objects/node.go
pkg/scheduler/objects/queue.go
pkg/scheduler/objects/queue_test.go
pkg/scheduler/objects/utilities_test.go
pkg/scheduler/partition.go
pkg/scheduler/partition_test.go
pkg/scheduler/placement/fixed_rule_test.go
pkg/scheduler/placement/placement_test.go
pkg/scheduler/placement/provided_rule_test.go
pkg/scheduler/placement/tag_rule_test.go
pkg/scheduler/placement/testrule_test.go
pkg/scheduler/placement/user_rule_test.go
pkg/scheduler/tests/recovery_test.go
pkg/scheduler/utilities_test.go
pkg/webservice/handlers_test.go

Logic for the placeholder allocation and swap of the placeholder with a
real allocation.
Includes partial unit tests, no smoke tests.
Requires the changes from YUNIKORN-497 from the SI

[YUNIKORN-476] placeholder allocation and swap

---

go.mod
go.sum

Update go mod files after upgrading the dependent version of scheduler-interface to v0.10.0

[YUNIKORN-602] update go mod files for v0.10.0 release

---

.github/PULL_REQUEST_TEMPLATE

Add Pull-request-template for yunikorn-core.
https://issues.apache.org/jira/browse/YUNIKORN-607
https://github.com/apache/incubator-yunikorn-core/pull/263/checks?check_run_id=2208126414

[YUNIKORN-607] Pull-request-template for yunikorn-core

---

pkg/webservice/handlers.go
pkg/webservice/handlers_test.go
pkg/webservice/webservice.go

A few sentences describing the overall goals of the pull request's commits.
First time? Check out the contributing guide - http://yunikorn.apache.org/community/how_to_contribute   
* Open an issue on Jira https://issues.apache.org/jira/browse/YUNIKORN/
* Put link here, and add [YUNIKORN-*Jira number*] in PR title, eg. `[YUNIKORN-2] Gang scheduling interface parameters`

YUNIKORN-645. Fixed status code issues, error handling issues etc

---

pkg/scheduler/objects/application.go
pkg/scheduler/objects/application_state.go
pkg/scheduler/partition_manager.go

Expose the reason of scheduling failures to the shim side. Shim side changes are at https://github.com/apache/incubator-yunikorn-k8shim/pull/258
https://issues.apache.org/jira/browse/YUNIKORN-657

Core side changes of YUNIKORN-657

---

pkg/scheduler/objects/queue.go
pkg/scheduler/partition.go
pkg/webservice/dao/queue_info.go
pkg/webservice/handlers.go
pkg/webservice/handlers_test.go
pkg/webservice/routes.go

YUNIKORN-415: Add "queues" REST API to fetch list of queues

---

pkg/scheduler/objects/queue.go
pkg/webservice/handlers.go
pkg/webservice/handlers_test.go
pkg/webservice/routes.go

YUNIKORN-416: Add "applications" REST API to fetch list of applications

---

go.mod
go.sum
pkg/scheduler/objects/application.go
pkg/scheduler/objects/application_state.go
pkg/scheduler/objects/application_test.go

We ned to introduce gang scheduling styles to able able to chose the behaviour if a gang scheduling application times out.
There can be two kind of styles defined:
"hard" - fail the application after timeout
"soft" - schedule the application as a normal, non gang scheduling application
https://issues.apache.org/jira/browse/YUNIKORN-582
For now the build will fail, because it depends on the scheduler-interface.
After the shim side tracked under https://issues.apache.org/jira/browse/YUNIKORN-679  changes are ready, we will need to test it end to end.

[YUNIKORN-582] Introduced soft/hard gang scheduling styles

---

pkg/scheduler/objects/application.go

After merging YUNIKORN-582, it was a bug related the transition from Resuming to Accepted state.
https://issues.apache.org/jira/browse/YUNIKORN-582

[YUNIKORN-582] Fixed soft Transition issue from Resuming to Accepted

---

go.mod
go.sum

A few sentences describing the overall goals of the pull request's commits.
First time? Check out the contributing guide - http://yunikorn.apache.org/community/how_to_contribute   
https://issues.apache.org/jira/browse/YUNIKORN-733

[YUNIKORN-733] Update shim and core dependencies on master branch

---

pkg/metrics/scheduler.go

Defining "allocatedContainers", "rejectedContainers", "schedulingErrors" and "releasedContainers" to initialize scheduler metrics is redundant in code.
It can be combined into "containerAllocation"
It can use a "prometheus.CounterVec" with different Prometheus labels
https://issues.apache.org/jira/browse/YUNIKORN-715

[YUNIKORN-715] Refactor YuniKorn core's scheduler metrics for container allocation

---

pkg/scheduler/objects/application.go

A few sentences describing the overall goals of the pull request's commits.
First time? Check out the contributing guide - http://yunikorn.apache.org/community/how_to_contribute   
https://issues.apache.org/jira/browse/YUNIKORN-756

[YUNIKORN-756] Set default scheduling policy to Hard for gang scheduling

---

pkg/webservice/handlers_test.go

add test to handler_test.go (see https://github.com/apache/incubator-yunikorn-core/pull/291#issuecomment-894020336)
https://github.com/apache/incubator-yunikorn-core/pull/291#issuecomment-894020336

[YUNIKORN-785] add test to handlers_test.go to cover properties check

---

pkg/webservice/dao/partition_info.go
pkg/webservice/dao/queue_info.go

1. usedcapacity -> usedCapacity
2. maxcapacity -> maxCapacity
3. absusedcapacity -> absUsedCapacity
- https://github.com/apache/incubator-yunikorn-web/pull/64
- https://github.com/apache/incubator-yunikorn-site/pull/78
https://issues.apache.org/jira/browse/YUNIKORN-794

[YUNIKORN-794] fix typo in REST APIs: usedcapacity -> usedCapacity, maxcapacity -> maxCapacity, absusedcapacity -> absUsedCapacity

---

pkg/common/configs/config_test.go
pkg/common/configs/configvalidator.go

Ensure partition names are unique in core.
https://issues.apache.org/jira/browse/YUNIKORN-697

YUNIKORN-697: Enforce partition name uniqueness in core

---

pkg/metrics/history/internal_metrics.go
pkg/metrics/history/internal_metrics_test.go
pkg/scheduler/partition.go
pkg/webservice/handlers.go
pkg/webservice/handlers_test.go
pkg/webservice/routes.go
pkg/webservice/state_dump.go

Add new REST interfaces to the web service:
* request a full state dump from Yunikorn
* enable writing full state information periodically to an external file
* disable periodic state dumps
https://issues.apache.org/jira/browse/YUNIKORN-940

[YUNIKORN-940] Periodic & on-demand state dump in Yunikorn

---

pkg/webservice/handlers_test.go
pkg/webservice/state_dump.go

There are some issues in the state dump tests.
Also, in state_dump.go, we should look for the "periodSeconds" parameter, not "period".
https://issues.apache.org/jira/browse/YUNIKORN-945

[YUNIKORN-945] state dump testing improvements

---

pkg/webservice/handlers.go
pkg/webservice/handlers_test.go

A slice is incorrectly created in `getApplicationsDAO()`. The initial length should be zero and the capacity should be `size`.
Extended an existing unit test for better coverage.
https://issues.apache.org/jira/browse/YUNIKORN-952

[YUNIKORN-952] nil pointer error in webservice.getApplicationJSON()

---

go.mod
go.sum

Update SI dependency to v0.12.0 in the 0.12.0 branch
https://issues.apache.org/jira/browse/YUNIKORN-896

[YUNIKORN-896] Updated SI to v0.12.0 tag

---

pkg/metrics/scheduler.go

Refactor YuniKorn core's scheduler metrics for node number and sorting latency
https://issues.apache.org/jira/browse/YUNIKORN-717
Existing test coverage

[YUNIKORN-717]Refactor YuniKorn core's scheduler metrics for node number and sorting latency

---

pkg/metrics/init.go
pkg/metrics/queue.go
pkg/metrics/scheduler.go

To improve YuniKorn core's queue-level and scheduler metrics:
- Differentiate queue level metrics with scheduler metrics, e.g. using "IncQueueApplicationsAccepted"
- Refactor related queue and scheduler metrics definitions
- Refactor related queue and scheduler metrics operation functions
- Update metrics naming and help messages 
- Update in-line comments and documentations
https://issues.apache.org/jira/browse/YUNIKORN-721
Existing tests

[YUNIKORN-721]Improve YuniKorn core's queue-level and scheduler metrics

---

pkg/events/event_publisher_test.go
pkg/examples/simple_example.go
pkg/plugins/plugins_test.go
pkg/scheduler/mock_plugin_test.go
pkg/scheduler/tests/mock_rm_callback.go
pkg/scheduler/tests/mock_rm_callback_test.go
pkg/scheduler/tests/plugin_test.go
pkg/webservice/handlers_test.go

Multiple implementations of ResourceManagerCallback interface in several test go files has been removed by introducing single common struct which implements ResourceManagerCallback interface
https://issues.apache.org/jira/browse/YUNIKORN-935

[YUNIKORN-935] Refactor resourcemanagercallback mock class

---

go.mod
pkg/common/configs/config.go
pkg/common/configs/config_test.go
pkg/scheduler/objects/application_graphviz_test.go
pkg/webservice/handlers.go
pkg/webservice/handlers_test.go

Go's ioutil package to be deprecated in 1.16
change ioutil to io or os
https://issues.apache.org/jira/projects/YUNIKORN/issues/YUNIKORN-1027

[YUNIKORN-1027] Go: deprecation of io/ioutil

---

pkg/scheduler/objects/application_test.go
pkg/scheduler/partition_test.go
pkg/scheduler/placement/placement.go
pkg/webservice/handlers_test.go

Missing "e" in the word "placment"
https://issues.apache.org/jira/browse/YUNIKORN-1137

[YUNIKORN-1137] Fix typo in placement related messages

---

pkg/scheduler/context.go
pkg/scheduler/context_test.go
pkg/scheduler/health_checker.go
pkg/scheduler/objects/queue.go
pkg/scheduler/objects/queue_test.go
pkg/scheduler/partition.go
pkg/webservice/handlers.go
pkg/webservice/handlers_test.go

informations and infos are not valid words.
rename the variables that end with informations and infos by removing the s.
https://issues.apache.org/jira/browse/YUNIKORN-1138

[YUNIKORN-1138] rename the variables that end with infos and informations

---

pkg/webservice/handlers_test.go

Add unit tests for handler calls getLogLevel and setLogLevel
[YUNIKORN-1399](https://issues.apache.org/jira/browse/YUNIKORN-1399)

[YUNIKORN-1399] Add unit tests for handler calls getLogLevel and setLogLevel

---

NOTICE

Update NOTICE file in root folder
https://issues.apache.org/jira/browse/YUNIKORN-1495

[YUNIKORN-1495]Update thr copyright years in NOTICE file to 2023

---

pkg/common/configs/configvalidator.go

add more detailed error message when validating maxApplications
N/A
https://issues.apache.org/jira/browse/YUNIKORN-2259
covered by existing unit tests
N/A
N/A

[YUNIKORN-2259] add more meaningful error message when the invalid config is caused by undefined maxapplications

---

pkg/webservice/handlers_test.go

add missing asserting for existing user/group and rename methods in TestSpecificUserAndGroupResourceUsage
N/A
https://issues.apache.org/jira/browse/YUNIKORN-2272
covered by unit test
N/A
N/A

[YUNIKORN-2272] refactor TestSpecificUserAndGroupResourceUsage

---

pkg/common/configs/config_test.go

Fix incorrect assertion condition in config_test.go and add some missing test cases.
N/A
https://issues.apache.org/jira/browse/YUNIKORN-2296
covered by unit tests
N/A
N/A

[YUNIKORN-2296] Incorrect assert condition in config_test.go

---

pkg/common/resources/resources_test.go

Improve `FitInScore` funtion's test coverage
https://issues.apache.org/jira/browse/YUNIKORN-2644

[YUNIKORN-2644] Improve FitInScore funtion's test coverage
