apache/yunikorn-core

pkg/cache/cluster_info.go, pkg/scheduler/scheduler.go, pkg/scheduler/schedulerevent/events.go, pkg/scheduler/scheduling_allocation_ask.go, pkg/scheduler/tests/scheduler_recovery_test.go, pkg/scheduler/tests/schedulertestutils.go
A couple of changes since last time
- removed `recovering` state from yunikorn-core
- let the core scheduler stay silly without maintaining a state, it just handles requests whatever a shim sends
- we'll add the `recovering` state in shim, so it only sends existing allocations to core under this state, new pending pods will be waiting after it exits the recovering state (recovery done).
=> recover scheduler state from previous allocated allocations

pkg/scheduler/tests/scheduler_recovery_test.go
During recovery, we need to send apps first before nodes. This UT is to add coverage for that.
=> add UT to cover the case of recovering apps before nodes

pkg/cache/partition_info.go, pkg/scheduler/tests/scheduler_recovery_test.go
During recovery, when we start to processing existing allocations, we should transit app's state from Accepted to Running, this was missed in the initial patch for recovery, this PR is to fix this issue.
=> application state is accepted after scheduler recovery

pkg/scheduler/placement/rule.go
Replace the new strings.ReplaceAll() method call with the old strings.Replace() call.
ReplaceAll was introduced in G0 1.12 as most of the calls use a -1 anyway.
Closes #37
=> Remove strings.ReplaceAll for Go 1.11 compatibility

pkg/common/security/acl.go, pkg/scheduler/placement/filter.go
In the ACL and filter when we check the groups we use the less restrictive user regexp.
It does not break behaviour but we should be using the correct regexp to make sure the configuration is correctly checked.
=> ACL and Filter use user regexp when they should use group regexp

pkg/scheduler/tests/scheduler_smoke_test.go
add a UT to cover the following case
- send requests that exceed total queue capacity
- verify capacity gets fully used, and left some requests pending
- release some existing allocations and that can give room for pending requests
=> add UT to test scheduling behaviors when exceeds queue capacity

pkg/log/logger.go, pkg/scheduler/tests/scheduler_smoke_test.go, pkg/scheduler/tests/schedulertestutils.go
There are some thread-safe issues in the mocked scheduler callback.
=> Fix a potential race condition in scheduler smoke test

pkg/scheduler/scheduling_queue.go
There may be a potential deadlock when:
(1) scheduling thread holds the lock of parent queue and waits for read lock of child queue (calling stack: Scheduler#singleStepSchedule -> Scheduler#findAllocationAsks -> Scheduler#findNextAllocationAskCandidate -> Scheduler#sortSubqueuesFromQueue -> SchedulingQueue#GetPendingResource) 
and meanwhile
(2) scheduler event handler holds the lock of child queue and waits for read lock of parent queue (calling stack: Scheduler#handleSchedulerEvent -> Scheduler#processAllocationUpdateEvent -> Scheduler#updateSchedulingRequest -> SchedulingQueue#IncPendingResource)
I think the proper sequence of nested lock should be from parent queue to child queue, the contrary way should be corrected.
Deadlock stacks:
=> Fix potential deadlock in SchedulingQueue

pkg/cache/application_state.go, pkg/cache/cluster_info.go, pkg/cache/partition_info.go, pkg/metrics/init.go, pkg/metrics/queue.go, pkg/metrics/scheduler.go, pkg/rmproxy/rmproxy.go
Remove the doOnce during the registration, to make sure each queue metrics are tracked.
=> Fix the issue that queue metrics was not registered correctly

pkg/common/resources/resources.go, pkg/common/resources/resources_test.go, pkg/scheduler/sorters.go, pkg/scheduler/sorters_test.go
For example:
queue1: allocated-resource:50, guaranteed-resource:100, usage-ratio=50/100=0.5
queue2: allocated-resource:100, guaranteed-resource:300, usage-ratio=0.33
After sorting queues, queue2 should be placed before queue1, but current result is opposite.
=> queue-usage-ratio should be compared separately when sorting queues

pkg/common/configs/configwatcher.go
This is a trivial improvement for config watcher to make sure it can be stopped in time and can solve  #62 (TestConfigWatcherExpiration UT fails intermittently).
=> Make sure config watcher can be stopped in time

Makefile, pkg/log/logger.go, pkg/scheduler/tests/scheduler_perf_test.go, pkg/scheduler/tests/schedulertestutils.go
Glad to see scheduler perf test is added, it is useful for us to know scheduling abilities quickly and debug the scheduling perf locally, I have some suggestions about this:
1. Now this test doesn't contain verification about correctness and will last for a few seconds, we have to wait more time to execute 'make test', I suppose to mark this test as non-short and default run 'go test -short'
2. Too many DEBUG logs will be printed in console when running this test, we can change log level dynamically to avoid this.
3. totalAllocations in the test should be 100000 instead of 10000, here I think it's better to adjust the test scale and don't have to wait all allocations are done. For waitForMinAllocations in schedulertestutils.go, we can replace the sleep condition 'allocLen != nAlloc' with …
=> Improve scheduler perf test

pkg/metrics/init.go, pkg/metrics/metrics_test.go, pkg/metrics/queue.go, pkg/metrics/scheduler.go
Names of node resource on K8s may contain some invalid characters for prometheus, for example: 'group/name' or 'group.name', we may encounter validation failures when registering node usage metrics. 
This PR proposes to Format metric names via replacing invalid characters(not in alpha-beta, numeric, '_' and ':' characters) with '\_' and add the prefix '\_' when metric name starts with a number.
=> Format metric names of node usage to avoid validation failures

pkg/cache/partition_info.go, pkg/scheduler/allocator.go, pkg/scheduler/scheduling_node.go, pkg/scheduler/tests/scheduler_recovery_test.go
When placement rule is enabled, job/task's queue name may or may not equal to queueName in pod's spec. For both fresh start and recovery case, we should enforce following rules
- app queue name is determined by the Placement Rule Manager
- task queue name is inherited from app
this way we can handle targetting queue consistently. Otherwise, we saw some failures like:
2020-01-17T19:10:40.329Z WARN cache/cluster_info.go:338 Failure while adding new node, node rejected with error queue does not exist or is not a leaf queue root.default
causing recovery timeout.
=> During recovery existing allocations should inherits queue name from the application

pkg/cache/cachetestutils.go, pkg/cache/initializer.go, pkg/cache/initializer_test.go, pkg/cache/partition_info.go, pkg/cache/queue_info.go, pkg/scheduler/partition_manager.go, pkg/scheduler/preemptor.go, pkg/scheduler/scheduling_application.go, pkg/scheduler/scheduling_queue.go, pkg/scheduler/scheduling_queue_test.go, pkg/scheduler/sorters.go, pkg/scheduler/sorters_test.go, pkg/scheduler/tests/scheduler_recovery_test.go, pkg/scheduler/tests/scheduler_smoke_test.go
Deadlock in the scheduler when restoring a node with allocations
Data race fixes around guaranteed resource of a queue and ask repeat
=> [YUNIKORN-6] Deadlock in the scheduler when restoring a node with allocations

pkg/log/logger_test.go
Remove the last code dependency for stretchr from the log testing.
=> [YUNIKORN-13] Remove stretchr/testify as a dependency

pkg/scheduler/scheduling_application.go
Looks like we are hitting some bug in zap, replacing duration with string and this error goes away
```
2020-03-27T13:30:26.553-0700	WARN	predicates/predictor.go:286	predicate failed	{"key": "CheckNodeUnschedulable", "fit": false, "reasons": [{"PredicateName":"NodeUnknownCondition","PredicateDesc":"node(s) had unknown conditions"}]}
2020-03-27T13:30:26.553-0700	DEBUG	scheduler/scheduling_node.go:213	running predicates failed	{"allocationId": "c7ed4d67-7069-11ea-b2f0-025000000001", "nodeID": "docker-desktop", "error": "predicate CheckNodeUnschedulable cannot be satisified, reason [Predicate NodeUnknownCondition failed]"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11ac568]
goroutine 51 [running]: …
```
=> [YUNIKORN-62] Fix time logging issue while doing reservation

docs/user-guide.md
Now helm v3 is the stable and default version according to helm official website(https://helm.sh/docs/), and there are lots of changes between v2 and v3.
Updates:
(1) Add chart name for install command, otherwise it will fail to install based on helm v3 with error: `Error: must either provide a name or specify --generate-name`
(2) Add description for uninstall command.
=> [YUNIKORN-36] Update install/uninstall commands of helm charts based on helm v3

pkg/scheduler/sorters.go, pkg/scheduler/sorters_test.go
Quick fix to change priority sorting to FIFO sorting for requests based on
the fact that the shim does not set priority.
=> [YUNIKORN-241] priority sorting quick fix

pkg/scheduler/scheduling_partition_test.go, pkg/scheduler/tests/scheduler_reservation_test.go
The reservation delay in certain tests is set to 10msec. This is on the
edge of being too long for a number of tests. It can cause unexpected
failures if the system the unit tests run on is "fast".
=> [YUNIKORN-302] use same reservation delay in all tests

pkg/scheduler/scheduler.go
Tested against `docker-desktop`. Response of /ws/v1/apps:
- Before the patch:
```json
[
{
"applicationID": "application-sleep-0001",
"usedResource": "[memory:500 vcore:100]",
"partition": "[mycluster]default",
"queueName": "root.default",
"submissionTime": 1600692185822369000,
"allocations": [
{
"allocationKey": "849185df-7e88-4478-bc86-dd9b4cea83e4",
"allocationTags": nil,
"uuid": "66a1013b-a278-4b6e-bd70-4ccb3d13eacb",
"resource": "[memory:500 vcore:100]",
"priority": "<nil>",
"queueName": "root.default",
"nodeId": "docker-desktop",
"applicationId": "application-sleep-0001",
"partition": "default"
}
],
"applicationState": "Starting"
},
...
```
- After the patch:
```json
[
{
"applicationID": "application-sleep-0001",
"usedResource": "[memory:500 vcore:100]",
"partition": …
```
=> [YUNIKORN-227] Include ask tags exposed via REST API

pkg/cache/queue_info.go, pkg/common/configs/configvalidator.go, pkg/entrypoint/entrypoint.go, pkg/plugins/plugins.go, pkg/scheduler/scheduler.go, pkg/scheduler/scheduling_application.go, pkg/scheduler/scheduling_partition.go
Rationalized a few log items in the core:
- increased log level from DEBUG to INFO when:
- adding a new managed queue 
- validating configs (once per partition). More granular logs are kept in DEBUG level
- registering scheduler plugins
- added a few extra lines in `entrypoint.go` to display what services have been started with YuniKorn
When the log levels are increased from DEBUG to INFO we will get rid of the following entries:
1. All the DEBUG level FTM log entries, like this:
```
2020-10-01T14:40:12.912+0200	DEBUG	scheduler/scheduler.go:231	enqueued event	{"eventType": "*schedulerevent.SchedulerUpdatePartitionsConfigEvent", "eventError": "json: unsupported type: chan *commonevents.Result", "currentQueueSize": 0}
```
I think we're fine to remove all these.
2. Outstanding request …
=> [YUNIKORN-429] Set default logging level to INFO

pkg/common/resources/resources.go, pkg/common/resources/resources_test.go
The String method of Resource is not nil safe which causes a panic to be
logged instead of a proper message.
=> [YUNIKORN-445] Panic in Resource.String()

go.mod, go.sum, pkg/rmproxy/rmevent/events.go, pkg/scheduler/context.go, pkg/scheduler/tests/mockscheduler_test.go, pkg/scheduler/tests/smoke_test.go
Because the new scheduler-interface change we need to rename AllocationReleaseRequest and AllocationReleaseResponse.
Please review @yangwwei 
Thanks.
=> [YUNIKORN-494]Rename the AllocationRelease Request and Response in core

pkg/scheduler/objects/application.go
While sorting applications the pending resources of an application are
accessed. This could happen while a different routine is updating the
pending resources when a Ask is modified.
Replace the pending resource object instead of cloning on retrieval as it
is faster.
=> [YUNIKORN-499] race condition in sorting apps

pkg/scheduler/partition.go, pkg/scheduler/partition_test.go
The allocations map in the partition is not needed anymore after the
cache removal. Updating and keeping the map in sync with the other
objects in the scheduler can cause a deadlock.
Remove the map and replace it with a simple counter for the web UI.
Simplify locking where possible to remove partition locks.
=> [YUNIKORN-461] remove allocations list from partition

pkg/webservice/handlers.go
Times in the rest interface should be in nano seconds. The application
submission time is converted into seconds causing display issues on
the web UI.
=> [YUNIKORN-542] App submission time in nano seconds

pkg/scheduler/context.go, pkg/scheduler/nodes_usage_monitor.go, pkg/scheduler/partition.go, pkg/scheduler/partition_test.go
When a node gets removed the node alocations get removed as part of the
cleanup phase. The node removal acquires the partition lock and does not
release it until all actions are done. This could cause a deadlock with
scheduling if the node being removed contains allocations for the same
application that is scheduled.
The node removal should only lock while updating the partition and
release before updating the apps and queues. Since node removal is
called as part of the cleanup of a failed add of a node the add flow is
changed inline with the removal to minimise lock time.
The partition lock was also held while placing applications. This is not
required as placing an application does not modify the partition until
everything is done. The lock should only be acquired at that point.
=> [YUNIKORN-551] Deadlock when removing node

pkg/scheduler/objects/application.go, pkg/scheduler/partition.go
Move the queue removal of the application outside of the partition lock.
The manipulations of the application object must not take the partition
lock. The application object itself handles locking as needed.
Add comments on locking for the partition.
=> [YUNIKORN-572] deadlock in moveTerminatedApp

pkg/scheduler/objects/application.go, pkg/scheduler/objects/application_state.go, pkg/scheduler/objects/application_state_test.go, pkg/scheduler/objects/application_test.go, pkg/scheduler/partition_test.go, pkg/scheduler/tests/reservation_test.go, pkg/webservice/handlers_test.go
With this fix a new state is introduced: Failing state. Also, Waiting state is renamed to Completing.
When we cleanup the placeholders, before moving the application into the terminating state (Completed or Failed)
we wait for the shim to release the allocations first.
=> [YUNIKORN-574] Wait for placeholder cleanup

pkg/metrics/init.go, pkg/metrics/metrics_collector.go, pkg/metrics/scheduler.go
Fix the metrics bug which get wrong amount of running containers.
https://issues.apache.org/jira/browse/YUNIKORN-627
=> [YUNIKORN-627]The container history graph does not go down when pods are gone

pkg/metrics/scheduler.go, pkg/scheduler/context.go
1) Container allocating latency stays at 0. The number of allocation attempts fluctuates normally.
2) Scheduler metrics definition is not consistent and sometimes hard to understand.
1) The metrics "allocating_latency_seconds" is not fully implemented or the implementation is missed in recent releases. For example, ObserveSchedulingLatency() is currently not called when allocating containers.
2) Scheduler metrics is implemented by multiple developers in the past while not following the same convention.
1) The top level container allocation latency can be captured by the main scheduling routine in `scheduler/context.go`. Reason: The `schedule()` method in `scheduler/context.go` is the entry point to process each partition in the scheduler, walk over each queue and app to check if anything …
=> [YUNIKORN-646] Implement missing metrics "allocating_latency_seconds" and refactor scheduler metrics

pkg/scheduler/context.go, pkg/webservice/handlers.go, pkg/webservice/handlers_test.go
REST API redesign changes has ended up in some redundant code which requires refactoring to make it clean and elegant. This JIRA takes care of below improvements:
1. Avoid repeating "Partition not found", "Queue not found" etc asserts.
2. Make use of utils.GetNormalizedPartitionName to avoid cluster id in partition name
https://issues.apache.org/jira/browse/YUNIKORN-678
=> YUNIKORN-678: Refactoring REST API re-design changes in handlers.go, handlers_test.go

pkg/scheduler/objects/application.go
After YUNIKORN-521, when a job is deleted, all its placeholders are cleaned up too. Although the pods are deleted, the allocations still persist in Yunikorn
https://issues.apache.org/jira/browse/YUNIKORN-724
=> [YUNIKORN-724] Cleaned-up placeholder allocations are still reported by Yunikorn

pkg/metrics/init.go, pkg/metrics/scheduler.go, pkg/rmproxy/rmproxy.go, pkg/scheduler/objects/application_state.go
The metrics naming and operations are sometimes confusing in the code due to not aligning with each other on similar concepts.
- Replace "totalApplicationsAdded" with "totalApplicationsAccepted"
- Update related metrics operation functions
https://issues.apache.org/jira/browse/YUNIKORN-713
=> [YUNIKORN-713] Align YuniKorn core's scheduler metrics with queue metrics for total applications accepted

Makefile
The license check run as part of the PR workflow always passes when run on linux.
The recursive grep redirect to a variable does not work.
https://issues.apache.org/jira/browse/YUNIKORN-771
NA
=> [YUNIKORN-771] make license-check fix for linux

pkg/scheduler/objects/queue.go, pkg/scheduler/objects/queue_test.go, pkg/webservice/dao/queue_info.go
That helps us observe the "application.sort.policy" through REST APIs. 
https://issues.apache.org/jira/browse/YUNIKORN-781
`TestGetPartitionQueues`
=> [YUNIKORN-781] Add  queue properties to the response of /ws/v1/partition/{partition}/queues

pkg/metrics/metrics_collector.go, pkg/metrics/metrics_collector_test.go
…ot depend on timer
Depending on timer makes TestHistoricalPartitionInfoUpdater unstable. It fails if the thread can't complete at the right time. Also, some methods are not covered by test.
https://issues.apache.org/jira/browse/YUNIKORN-786
=> [YUNIKORN-786] refactor TestHistoricalPartitionInfoUpdater to make it not depend on timer

pkg/metrics/scheduler.go
Refactor scheduler.go for more consistency and readability
Defining "totalApplicationRunning" and "totalApplicationCompleted" to initialize scheduler metrics is redundant in code.
It can be combined into one "application" metrics
It can use a "prometheus.CounterVec" with different Prometheus labels
https://issues.apache.org/jira/browse/YUNIKORN-716
=> [Yunikorn-716] Refactor YuniKorn core's scheduler metrics for application status

pkg/webservice/handlers.go, pkg/webservice/handlers_test.go
… no node
`PartitionContext#totalPartitionResource` is null if the partition has no node. We need to check null before converting it to dao object. 
https://issues.apache.org/jira/browse/YUNIKORN-817
=> [YUNIKORN-817] Avoid NPE in /ws/v1/nodes/utilization REST API when partition has no node

go.mod, go.sum, pkg/common/resources/resources.go, pkg/metrics/init.go, pkg/scheduler/context.go, pkg/scheduler/drf_preemption_policy.go, pkg/scheduler/objects/application.go, pkg/scheduler/objects/node.go, pkg/scheduler/objects/node_collection.go, pkg/scheduler/objects/node_collection_test.go, pkg/scheduler/objects/node_iterator.go, pkg/scheduler/objects/node_iterator_test.go, pkg/scheduler/objects/node_listener.go, pkg/scheduler/objects/node_test.go, pkg/scheduler/objects/nodesorting.go, pkg/scheduler/objects/queue.go, pkg/scheduler/objects/sorters.go, pkg/scheduler/objects/sorters_test.go, pkg/scheduler/partition.go, pkg/scheduler/partition_test.go
Improves the performance of node sorting by maintaining an ordered B-Tree of nodes rather than sorting the entire node list on demand. This patch does not introduce any external behavior changes.
https://issues.apache.org/jira/browse/YUNIKORN-807
All local unit tests pass. Scheduling under load should be verified.
N/A
=> [YUNIKORN-807] Improve performance of node sorting.

pkg/scheduler/objects/allocation_ask_test.go
Add unit test to improve coverage
https://issues.apache.org/jira/browse/YUNIKORN-838
Use command "make test" to create coverage.txt and then use "go tool cover -func=coverage.txt" to check
=> [YUNIKORN-838] Improve coverage of allocation_ask.go

pkg/common/configs/config.go, pkg/common/configs/configvalidator.go, pkg/common/resources/resources.go, pkg/scheduler/objects/node.go, pkg/scheduler/objects/nodesorting.go, pkg/scheduler/objects/nodesorting_test.go, pkg/scheduler/objects/sorters_test.go, pkg/scheduler/partition.go, pkg/scheduler/partition_test.go, pkg/scheduler/utilities_test.go
Updates node sorting algorithms to take into account resource weights when calculating scores. Scores are now based on percentage of a node utilized rather than absolute values. This prevents priority inversion when we have resources with large absolute values. By default, vcores and memory are given equal weight.
https://issues.apache.org/jira/browse/YUNIKORN-847
Unit tests were performed as well as manual testing of various workloads on a test cluster.
=> [YUNIKORN-847] Use resource weighting for node sorting.

pkg/scheduler/context.go, pkg/scheduler/partition.go, pkg/scheduler/partition_manager.go, pkg/scheduler/partition_manager_test.go
All functions in `partition_manager` are using pass-by-value so setting the `stop` flag to true can't terminate other threads.
```
func (manager partitionManager) Stop() {
manager.stop = true
}
```
Also, the thread used to cleanup expired app can't be stopped quickly after removing partition because it needs to sleep for 24 hours.
```
func (manager partitionManager) cleanupExpiredApps() {
for {
if manager.stop {
break
}
manager.pc.cleanupExpiredApps()
time.Sleep(appRemovalInterval)
}
}
```
https://issues.apache.org/jira/browse/YUNIKORN-832
=> [YUNIKORN-832] Updating config can't remove partition

pkg/scheduler/context.go
… instead of read lock
the delete operation is a kind of write operation, so it should use write lock.
https://issues.apache.org/jira/browse/YUNIKORN-862
=> [YUNIKORN-862] ClusterContext#removePartition ought to use write lock

pkg/metrics/init.go, pkg/metrics/queue.go, pkg/scheduler/objects/queue.go
Queue-level capacity metrics (guaranteed resource, max resource) are not implemented in code.
Users need to adjust the capacity threshold manually from any monitoring dashboard if their queue capacity changes.
It is hard for users to evaluate and demonstrate historical usage trend. Not a small amount of manual work is needed by users or dev ops.
https://issues.apache.org/jira/browse/YUNIKORN-828
Existing test coverage
=> [YUNIKORN-828]Add YuniKorn core's queue-level capacity (guaranteed, max) metrics

go.mod, go.sum, pkg/common/configs/config.go, pkg/common/configs/config_test.go, pkg/common/configs/configvalidator.go, pkg/scheduler/partition.go, pkg/scheduler/partition_test.go, pkg/scheduler/utilities_test.go, pkg/webservice/handlers_test.go, pkg/webservice/state_dump.go
Location of the state dump file should be configurable instead of hardcoded. PR also provides a default retention policy to ensure the file does not grow unbounded.   
* https://issues.apache.org/jira/browse/YUNIKORN-949
* Modified tests in handlers_test.go and manual testing
=> [YUNIKORN-949] Location of the state dump file should be configurable

pkg/scheduler/ugm/manager.go, pkg/scheduler/ugm/manager_test.go, pkg/webservice/handlers.go, pkg/webservice/handlers_test.go, pkg/webservice/routes.go
In the REST interface we currently only expose users and groups.
Like we do with applications we should add individual user and group endpoints for usage information:
/ws/v1/partition/{partition}/usage/user/{user}
/ws/v1/partition/{partition}/usage/group/{group}
* Open an issue on Jira https://issues.apache.org/jira/browse/YUNIKORN-1439
* Put link here, and add [YUNIKORN-*Jira number*] in PR title, eg. `[YUNIKORN-2] Gang scheduling interface parameters`
=> [YUNIKORN-1439] expose user and group endpoints

pkg/common/configs/config_test.go, pkg/common/configs/configvalidator.go, pkg/common/configs/configvalidator_test.go, pkg/scheduler/placement/fixed_rule.go, pkg/scheduler/placement/provided_rule.go, pkg/scheduler/placement/rule.go, pkg/scheduler/placement/tag_rule.go, pkg/scheduler/placement/testrule.go, pkg/scheduler/placement/types/types.go, pkg/scheduler/placement/user_rule.go
Validate the placement rules on a best effort basis to see whether it refers to queues which are not parents or not available.
https://issues.apache.org/jira/browse/YUNIKORN-1568
=> [YUNIKORN-1568] Placement rules should be validated during config update

pkg/common/configs/config_test.go, pkg/common/configs/configvalidator.go
Wildcard interpretation
Wildcard can only be used as the only entry in the limit object according to the documentation. There can be multiple limit objects in the overall limits for a queue. As part of this design the interpretation of the wildcard needs to be defined. Wildcards interpretation is related to the ordering of the limit objects in the overall limits object. The usage and interpretation will be different for users and groups. 
In general terms: allowing a wildcard in the user or group list only as part of the last entry of the limits list. After the wildcard has been added for either the user or group list we do not allow a user or group list with a non wildcard entry. This is especially important for the group resolution. It does allow specifying a user and group wildcard …
=> [YUNIKORN-1603] Configuration processing to support limit new wildcard interpretation syntax checking

pkg/webservice/handlers.go
We have Originator flag in the AllocationAskDAOInfo for restAPI.
But we don't assign the value for getAllocationAskDAO.
* Open an issue on Jira https://issues.apache.org/jira/browse/YUNIKORN-1737
* Put link here, and add [YUNIKORN-*Jira number*] in PR title, eg. `[YUNIKORN-2] Gang scheduling interface parameters`
=> [YUNIKORN-1737] Originator flag for AllocationAskDAOInfo don't assign for construct in getAllocationAskDAO.

pkg/metrics/queue.go
Add the missing states in the help message of `appMetricsLabel`
https://issues.apache.org/jira/browse/YUNIKORN-2242
=> [YUNIKORN-2242] Fix incorrect help message of queue metrics

pkg/webservice/handlers.go, pkg/webservice/handlers_test.go
The endpoint `/ws/v1/partition/{partitionName}/usage/users` and `/ws/v1/partition/{partitionName}/usage/groups`
will return nil when user / group usages are nonexistent. The return type is expected to be array, so it seems to me the empty array is more suitable to be returned.
N/A
https://issues.apache.org/jira/browse/YUNIKORN-2190
covered by unit tests
N/A
N/A
=> [YUNIKORN-2190] Using empty array to replace null response from /ws/v1/partition/{partitionName}/usage/users

pkg/webservice/handlers_test.go
remove `configStateDumpFilePath` in test.
N/A
https://issues.apache.org/jira/browse/YUNIKORN-2298
covered by unit tests
N/A
N/A
=> [YUNIKORN-2298] remove `configStateDumpFilePath` from handlers_test.go

pkg/events/event_publisher_test.go
"TestNoFillWithoutEventPluginRegistered" might not wait enough time to check a certain condition. Use `WaitForCondition()` instead of the hard-coded sleep.
https://issues.apache.org/jira/browse/YUNIKORN-2302
=> [YUNIKORN-2302] TestNoFillWithoutEventPluginRegistered is flaky

pkg/scheduler/objects/queue.go, pkg/scheduler/partition_test.go
Don't set resources from tags on the recovery queue.
This PR is for branch-1.5.
https://issues.apache.org/jira/browse/YUNIKORN-2642
=> [YUNIKORN-2642] Don't set resources on the recovery queue
